/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.femaleblogdata;

import com.ibm.swat.password.ReturnCode;
import com.ibm.swat.password.cwa2;
import java.util.Hashtable;

import javax.naming.NamingException;
import javax.swing.JOptionPane;

/**
 *
 * @author KshiteejManojVENDORG
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        loginDisplay = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("UserName : ");

        jLabel3.setText("Password :");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("RSC Technical Vitality Data Extractor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(153, 153, 153))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addGap(63, 63, 63)
                .addComponent(loginDisplay, javax.swing.GroupLayout.PREFERRED_SIZE,47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static boolean validateUser(String user, String pass, String group) {
	boolean ret = false;
	Hashtable row;
	try
	{
		cwa2 CWA2 = new cwa2();
		ret = CWA2.authenticate_throw(user,pass, "ldap://bluepages.ibm.com:389");
		if (ret==true)
		{
			System.out.println("User " + user + " Authenticated");
			//mylogger.updateLog_INFO("User " + user + " Authenticated");
			//JOptionPane.showMessageDialog(null,"User " + user + " Authenticated");
			/*boolean tmp=false;
			ReturnCode rc= CWA2.inAGroup(user,group);
			
			if(rc.getCode()==5 && rc.getMessage()=="User Not In Group")
				ret=false;
			else
				ret=true;
				
			//JOptionPane.showMessageDialog(null,rc.toString());
			System.out.println(user + " " + rc.getMessage()+ " "+group);
			mylogger.updateLog_INFO(user + " " + rc.getMessage()+ " "+group);*/
			
		}
		else
		{
			System.out.println("User " + user + " Not Authenticated");
			//mylogger.updateLog_WARNING("User " + user + " Not Authenticated");
		}	
        
	}	
	catch (Exception e)
	{
		System.out.println(" Error "+ e);
                System.exit(0);
		//mylogger.updateLog_WARNING(e.getMessage());
		//mylogger.updateLog_WARNING("This is the network issue...please check your network connectivity!!!");
    } 
	return ret;   
	} 

public static boolean isValidBlueGrpUser(String user, String pass, String group) {
	boolean isValid = false;
	boolean isValid_BG = false;
	try
	{
		cwa2 CWA2 = new cwa2();
		isValid = CWA2.authenticate_throw(user,pass, "ldap://bluepages.ibm.com:389");
		if (isValid==true)
		{
			ReturnCode rc= CWA2.inAGroup(user,group);
			
			if(rc.getCode()==5 && rc.getMessage()=="User Not In Group")
				isValid_BG=false;
			else
				isValid_BG=true;
				
			//JOptionPane.showMessageDialog(null,rc.toString());
			System.out.println(user + " " + rc.getMessage()+ " "+group);
			//mylogger.updateLog_INFO(user + " " + rc.getMessage()+ " "+group);
			
		}		  
		/*else
		{
			System.out.println("User " + user + " Not Authenticated");
			mylogger.updateLog_WARNING("User " + user + " Not Authenticated");
			
		}	
                */
		//return isValid_BG;
	}	
	catch (javax.naming.CommunicationException e)
	{
		JOptionPane.showMessageDialog(null,"Login fails, make sure you are connected to IBM Network");
		e.printStackTrace();
		
		
		//mylogger.updateLog_WARNING(e.getMessage());
		//mylogger.updateLog_WARNING("This is the network issue...please check your network connectivity!!!");
    }
	catch (Exception e) {
		e.printStackTrace();
		JOptionPane.showMessageDialog(null, "ERR: Invalid login credentials !");
	}
	
	  return isValid_BG;
	}
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        boolean login = isValidBlueGrpUser(userName.getText(),password.getText(),"RSC_BO");
           /*if (login == false) {
        	   loginDisplay.setText("ERR: Invalid login credentials !");
           }*/
           if (login == true) {
               this.setVisible(false);
               new FemaleBlogDataDisplay(userName.getText()).setVisible(true);
           }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private static javax.swing.JLabel loginDisplay;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
